--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "REPO"."CLIENTE" 
   (	"IDCLI" NUMBER, 
	"NOMCLI" VARCHAR2(100 BYTE), 
	"APECLI" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "REPO"."PRODUCTO" 
   (	"IDPRO" NUMBER, 
	"NOMPRO" VARCHAR2(100 BYTE), 
	"DESCPRO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFESIONAL
--------------------------------------------------------

  CREATE TABLE "REPO"."PROFESIONAL" 
   (	"IDPRF" NUMBER, 
	"NOMPPF" VARCHAR2(100 BYTE), 
	"APEPF" VARCHAR2(100 BYTE), 
	"TIPPROF" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICO
--------------------------------------------------------

  CREATE TABLE "REPO"."SERVICO" 
   (	"IDSERV" NUMBER, 
	"TIPSERV" VARCHAR2(20 BYTE), 
	"PRECSERV" NUMBER(*,0), 
	"IDPRF" NUMBER, 
	"IDPRO" NUMBER, 
	"IDCLI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GEN_IDENTITY
--------------------------------------------------------

   CREATE SEQUENCE  "REPO"."SEQ_GEN_IDENTITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into REPO.CLIENTE
SET DEFINE OFF;
Insert into REPO.CLIENTE (IDCLI,NOMCLI,APECLI) values ('5','Juan','Quispe Avalos');
REM INSERTING into REPO.PRODUCTO
SET DEFINE OFF;
REM INSERTING into REPO.PROFESIONAL
SET DEFINE OFF;
REM INSERTING into REPO.SERVICO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PROFESIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPO"."PROFESIONAL_PK" ON "REPO"."PROFESIONAL" ("IDPRF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPO"."SERVICO_PK" ON "REPO"."SERVICO" ("IDSERV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPO"."CLIENTE_PK" ON "REPO"."CLIENTE" ("IDCLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPO"."PRODUCTO_PK" ON "REPO"."PRODUCTO" ("IDPRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "REPO"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("IDPRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REPO"."PRODUCTO" MODIFY ("IDPRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "REPO"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDCLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REPO"."CLIENTE" MODIFY ("IDCLI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESIONAL
--------------------------------------------------------

  ALTER TABLE "REPO"."PROFESIONAL" ADD CONSTRAINT "PROFESIONAL_PK" PRIMARY KEY ("IDPRF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REPO"."PROFESIONAL" MODIFY ("IDPRF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICO
--------------------------------------------------------

  ALTER TABLE "REPO"."SERVICO" ADD CONSTRAINT "SERVICO_PK" PRIMARY KEY ("IDSERV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REPO"."SERVICO" MODIFY ("IDSERV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SERVICO
--------------------------------------------------------

  ALTER TABLE "REPO"."SERVICO" ADD CONSTRAINT "SERVICO_FK1" FOREIGN KEY ("IDPRF")
	  REFERENCES "REPO"."PROFESIONAL" ("IDPRF") ENABLE;
  ALTER TABLE "REPO"."SERVICO" ADD CONSTRAINT "SERVICO_FK2" FOREIGN KEY ("IDPRO")
	  REFERENCES "REPO"."PRODUCTO" ("IDPRO") ENABLE;
  ALTER TABLE "REPO"."SERVICO" ADD CONSTRAINT "SERVICO_FK3" FOREIGN KEY ("IDCLI")
	  REFERENCES "REPO"."CLIENTE" ("IDCLI") ENABLE;
